apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis-public
spec:
  replicas: 2
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: redis
        image: registry.***.com:5000/v1/redis:3.0.7
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 800m
            memory: 1000Mi

----------------------
apiVersion: v1
kind: Service
metadata:
  name:  redis
  labels:
    name: redis-public
spec:
  type: NodePort
  clusterIP: 192.168.3.79
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30079
  selector:
    name: redis-master
