tomcat nfs

apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-web
spec:
  replicas: 2
  selector:
    role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: web
        image: 192.168.5.69:5002/xdgc/tomcat7-oracle.latest:latest
        ports:
          - name: web
            containerPort: 6379
        volumeMounts:
            # name must match the volume name below
            - name: nfs
              mountPath: "/data/nfs"
      volumes:
      - name: nfs
        nfs:
          server: 192.168.5.69
          path: "/"


kind: Service
apiVersion: v1
metadata:
  name: nfs-web
spec:
  ports:
    - port: 6379
  selector:
    role: web-frontend



